export const SET_HIGHLIGHTED_CATEGORY = "SET_HIGHLIGHTED_CATEGORY";
export const REMOVE_HIGHLIGHTED_CATEGORY = "REMOVE_HIGHLIGHTED_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const DELETE_LOCATION = "DELETE_LOCATION";
